# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_shopcar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
