# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190212_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
